### ISSUE TITLE
Pausing for 10 seconds actually pauses for 20+ seconds

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/PowerMonitoring#55]
While looking through current sensing logs for the many unrelated issues, I spotted that whenever the 10s pause notice
```
2024-12-11T08:58:27.702902+00:00 AdvancedPowerPi docker-current-sensing[1171]: ERROR:main.measure:Sample Error for device mfm1: Modbus Error: [Input/Output] ERROR: No response received after 3 retries - pausing for 10 seconds
```
appears, the next attempt isn't 10 seconds later. Look at the timestamps:
```
2024-12-11T08:58:27.702837+00:00 AdvancedPowerPi docker-current-sensing[1171]: pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 3 retries
2024-12-11T08:58:27.702902+00:00 AdvancedPowerPi docker-current-sensing[1171]: ERROR:main.measure:Sample Error for device mfm1: Modbus Error: [Input/Output] ERROR: No response received after 3 retries - pausing for 10 seconds
2024-12-11T08:58:27.712416+00:00 AdvancedPowerPi docker-current-sensing[1171]: INFO:main.mqtt_out:pub topic:error/sensing_dc msg:{'type': 'device', 'id': 'mfm1', 'reason': 'Modbus Error: [Input/Output] ERROR: No response received after 3 retries', 'timestamp': '2024-12-11T08:58:27.700405+00:00'}
2024-12-11T08:58:49.734444+00:00 AdvancedPowerPi docker-current-sensing[1171]: ERROR:core.interface_modules.modbus:ERROR: exception in pymodbus Modbus Error: [Input/Output] ERROR: No response received after 3 retries
2024-12-11T08:58:49.735365+00:00 AdvancedPowerPi docker-current-sensing[1171]: ERROR:core.device_modules.multi_function_meter_HOBUT:Traceback (most recent call last):
2024-12-11T08:58:49.735685+00:00 AdvancedPowerPi docker-current-sensing[1171]:   File "/app/core/device_modules/multi_function_meter_HOBUT.py", line 87, in sample
2024-12-11T08:58:49.735973+00:00 AdvancedPowerPi docker-current-sensing[1171]:     readings[self.varI1] = await self.read_modbus_register(self.regI1)
2024-12-11T08:58:49.737057+00:00 AdvancedPowerPi docker-current-sensing[1171]:   File "/app/core/device_modules/multi_function_meter_HOBUT.py", line 135, in read_modbus_register
2024-12-11T08:58:49.737380+00:00 AdvancedPowerPi docker-current-sensing[1171]:     return await result
```
The jump is from 27 seconds past the minute to 49. Why 22 seconds? I might expect either 10 or 10+sample interval - which according to the `pm_a_3p.toml` config preset that I am using, is 
```
[measurement.config]
    period = 1.0 # seconds
```

As for where this pause actually appears in the code, a search reveals:

https://github.com/DigitalShoestringSolutions/PowerMonitoring/blob/df38c70431d566ed3eb3d1e1ffcee1d624f1db23/current_sensing/code/measure.py#L80-L118

Assuming `await asyncio.sleep(10)` is to be trusted, what else could cause this discrepancy? Are two of those `except` blocks running? (Shouldn't be, `except` should select only one outcome. Unless one error class instance inherited properties from another?)
Whilst this issue in itself is of minimal consequence, it does add to the air of mystery as to what goes on in this module.

**Comment by tobyaharris** [comment]
Seems we can't trust the timestamps in docker logs at all. They can get batched and sometimes be several minutes off when they were created. Have a look at some messages which include a timestamp in the body (some MODBUS related ones).

So maybe this is a non-issue?
